// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually
  // tutorialSidebar: [

  //   'index',
  //   {
  //     type: 'category',
  //     label: 'XRP Tutorials',
  //     items: [
  //       'tutorials/XRP_Arcade_Drive/arcade-drive',
  //       'tutorials/XRP_Tank_Drive/tutorial_XRP_tank_drive',
  //       'tutorials/WPILib_VS CodeDocs/tutorial_XRP_WPILib',
  //       'tutorials/XRP_Run_Code/tutorial_XRP_run_code',
  //       'tutorials/XRP_project/tutorial_XRP_Project'
  //     ],
  //   },
  // ],
};

export default sidebars;
